# Generated by Django 5.1.7 on 2025-04-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='nombre_grupo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
