# Generated by Django 5.1.7 on 2025-04-10 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('mensaje', 'Mensaje nuevo'), ('voluntariado', 'Nueva oferta de voluntariado'), ('comentario', 'Nuevo comentario en tu publicación'), ('me_gusta', 'Me gusta en tu publicación'), ('insignia', 'Nueva insignia obtenida'), ('follow', 'Nuevo seguidor')], max_length=20),
        ),
    ]
