# Generated by Django 5.1.7 on 2025-04-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_notificacion_actor_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
