# Generated by Django 5.1.7 on 2025-04-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_notificacion_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='url',
        ),
    ]
