# Generated by Django 5.1.7 on 2025-04-29 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_notificacion_publicacion'),
        ('voluntariados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='voluntariado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_voluntariado', to='voluntariados.voluntariado'),
        ),
    ]
