# Generated by Django 5.1.7 on 2025-04-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLogin', '0002_categoriavoluntariado_habilidad_user_biografia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
