# Generated by Django 5.1.7 on 2025-05-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLogin', '0003_user_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
