# Generated by Django 5.1.7 on 2025-03-18 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionLogin', '0002_categoriavoluntariado_habilidad_user_biografia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='voluntariados/')),
                ('curso_previo', models.TextField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(to='gestionLogin.categoriavoluntariado')),
                ('entidad', models.ForeignKey(limit_choices_to={'es_entidad': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voluntariado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntariados.voluntariado')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_participacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voluntariado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntariados.voluntariado')),
            ],
        ),
    ]
