# Generated by Django 5.1.7 on 2025-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacionvoluntariado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
