# Generated by Django 5.1.7 on 2025-05-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0002_participacionvoluntariado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacionvoluntariado',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
