# Generated by Django 5.1.7 on 2025-05-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0003_participacionvoluntariado_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacionvoluntariado',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
