# Generated by Django 5.1.7 on 2025-05-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0005_participacionvoluntariado_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacionvoluntariado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('expulsado', 'Expulsados')], default='pendiente', max_length=10),
        ),
    ]
