# Generated by Django 5.1.7 on 2025-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariados', '0008_alter_valoracionvoluntariado_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntariado',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
